'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),https=require('node:https'),crypto=require('node:crypto'),{execFileSync}=require('node:child_process');
const {importCredentials,resolveEndpoint,requestStatus,validateURL}=require('../src/server/mcp/discovery-client');
function fixture(t){const dir=fs.mkdtempSync(path.join(fs.realpathSync(os.tmpdir()),'penecho-discovery-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));fs.writeFileSync(dir+'/openssl.cnf','[req]\ndistinguished_name=dn\n[dn]\n');execFileSync('openssl',['req','-config',dir+'/openssl.cnf','-x509','-newkey','rsa:2048','-nodes','-keyout',dir+'/key','-out',dir+'/cert','-days','1','-subj','/CN=Test CA','-addext','basicConstraints=critical,CA:TRUE','-addext','keyUsage=critical,keyCertSign,cRLSign','-addext','subjectAltName=IP:127.0.0.1'],{stdio:'ignore'});execFileSync('openssl',['req','-config',dir+'/openssl.cnf','-new','-newkey','rsa:2048','-nodes','-keyout',dir+'/leaf-key','-out',dir+'/leaf.csr','-subj','/CN=localhost'],{stdio:'ignore'});fs.writeFileSync(dir+'/ext','basicConstraints=critical,CA:FALSE\nsubjectAltName=IP:127.0.0.1\nextendedKeyUsage=serverAuth\n');execFileSync('openssl',['x509','-req','-in',dir+'/leaf.csr','-CA',dir+'/cert','-CAkey',dir+'/key','-CAcreateserial','-out',dir+'/leaf-cert','-days','1','-extfile',dir+'/ext'],{stdio:'ignore'});const certificatePem=fs.readFileSync(dir+'/cert','utf8'),hostId=crypto.createHash('sha256').update(new crypto.X509Certificate(certificatePem).raw).digest('hex');return {dir,certificatePem,hostId,accessToken:'a'.repeat(64),stateDirectory:dir+'/state'};}
async function server(t,f,startedAt){let received=0;const s=https.createServer({cert:fs.readFileSync(f.dir+'/leaf-cert'),key:fs.readFileSync(f.dir+'/leaf-key')},(req,res)=>{received++;assert.equal(req.headers.authorization,`Bearer ${f.accessToken}`);res.end(JSON.stringify({hostId:f.hostId,startedAt}));});await new Promise(r=>s.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>s.close(r)));return {url:`https://127.0.0.1:${s.address().port}/mcp`,received:()=>received};}
test('real HTTPS discovery selects newest, cache avoids discovery, concurrent callers share discovery',async t=>{const f=fixture(t),a=await server(t,f,100),b=await server(t,f,200);importCredentials(f,f);let calls=0;const discover=async()=>{calls++;await new Promise(r=>setTimeout(r,100));return [a.url,b.url];};const values=await Promise.all([resolveEndpoint({...f,discover}),resolveEndpoint({...f,discover})]);assert.equal(calls,1);assert.ok(values.every(v=>v.url===b.url));await resolveEndpoint({...f,discover:()=>{throw Error('must not discover');}});assert.equal(fs.statSync(path.join(f.stateDirectory,'hosts',f.hostId,'credentials.json')).isFile(),true);assert.ok(!fs.readFileSync(path.join(f.stateDirectory,'hosts',f.hostId,'endpoint.json'),'utf8').includes('accessToken'));});
test('unknown CA never receives authorization and public URLs rejected',async t=>{const f=fixture(t),other=fixture(t),s=await server(t,other,100);await assert.rejects(requestStatus(s.url,f));assert.equal(s.received(),0);assert.throws(()=>validateURL('https://8.8.8.8/mcp'));assert.throws(()=>importCredentials({...f,hostId:'b'.repeat(64)},f));});
test('failed cache discovers and state symlinks fail closed',async t=>{const f=fixture(t);importCredentials(f,f);const dir=path.join(f.stateDirectory,'hosts',f.hostId);fs.writeFileSync(dir+'/endpoint.json',JSON.stringify({hostId:f.hostId,url:'https://127.0.0.1:1/mcp'}));const s=await server(t,f,100);const result=await resolveEndpoint({...f,discover:async()=>[s.url]});assert.equal(result.url,s.url);fs.unlinkSync(dir+'/endpoint.json');fs.symlinkSync(f.dir+'/cert',dir+'/endpoint.json');await assert.rejects(resolveEndpoint(f),/Symbolic/);});
test('separate CLI processes share lock and stale locks recover',async t=>{const f=fixture(t);importCredentials(f,f);const {spawn}=require('node:child_process'),modulePath=require.resolve('../src/server/mcp/discovery-client');const code=`const fs=require('node:fs');const {resolveEndpoint}=require(${JSON.stringify(modulePath)});const options=${JSON.stringify({hostId:f.hostId,stateDirectory:f.stateDirectory})};resolveEndpoint({...options,request:async()=>({hostId:options.hostId,startedAt:100}),discover:async()=>{fs.appendFileSync(${JSON.stringify(f.dir+'/broadcasts')},'x');await new Promise(r=>setTimeout(r,250));return ['https://127.0.0.1:3210/mcp'];}}).then(()=>{},()=>{process.exitCode=1;});`;
const run=()=>new Promise((resolve,reject)=>{const p=spawn(process.execPath,['-e',code],{stdio:'ignore'});p.on('error',reject);p.on('close',n=>n===0?resolve():reject(Error('Child failed')));});await Promise.all([run(),run()]);assert.equal(fs.readFileSync(f.dir+'/broadcasts','utf8'),'x');const dir=path.join(f.stateDirectory,'hosts',f.hostId);fs.unlinkSync(dir+'/endpoint.json');fs.mkdirSync(dir+'/discovery.lock');fs.utimesSync(dir+'/discovery.lock',new Date(0),new Date(0));await run();assert.equal(fs.readFileSync(f.dir+'/broadcasts','utf8'),'xx');});
test('CLI normal output redacts token and export is explicit',async t=>{const f=fixture(t);const bundle=f.dir+'/trust.json';fs.writeFileSync(bundle,JSON.stringify(f));const {main}=require('../src/server/mcp/discovery-client');let text='';const options={stateDirectory:f.stateDirectory,stdout:{write:s=>{text+=s;}},stderr:{write:s=>{text+=s;}},request:async()=>({hostId:f.hostId,startedAt:1}),discover:async()=>['https://127.0.0.1:3200/mcp']};assert.equal(await main(['--import',bundle],options),0);assert.ok(!text.includes(f.accessToken));text='';assert.equal(await main(['--host-id',f.hostId,'--client','json'],options),0);assert.ok(text.includes(f.accessToken));});
test('CLI diagnostics are specific and never echo untrusted messages',async t=>{const f=fixture(t);importCredentials(f,f);const {main,diagnostic}=require('../src/server/mcp/discovery-client');for(const code of ['AUTH_REJECTED','ERR_TLS_CERT_ALTNAME_INVALID','UNABLE_TO_VERIFY_LEAF_SIGNATURE','ECONNREFUSED']){let output='';const exit=await main(['--host-id',f.hostId],{stateDirectory:f.stateDirectory,discover:async()=>['https://127.0.0.1:1234/mcp'],request:async()=>{throw Object.assign(Error(f.accessToken+' -----BEGIN CERTIFICATE-----'),{code});},stderr:{write:s=>{output+=s;}}});assert.equal(exit,1);assert.equal(JSON.parse(output).code,diagnostic({code}).code);assert.ok(!output.includes(f.accessToken));assert.ok(!output.includes('BEGIN CERTIFICATE'));}assert.equal(diagnostic({code:'EACCES',message:f.accessToken}).code,'PERMISSION_DENIED');assert.equal(diagnostic({code:'CONFIG_CONFLICT'}).code,'CONFIG_CONFLICT');});
test('CLI native configuration retains resolved endpoint fields',async t=>{const f=fixture(t);importCredentials(f,f);const {main}=require('../src/server/mcp/discovery-client');let output='';assert.equal(await main(['--host-id',f.hostId,'--client','claude'],{stateDirectory:f.stateDirectory,home:f.dir,env:{},discover:async()=>['https://127.0.0.1:1234/mcp'],request:async()=>({hostId:f.hostId,startedAt:1}),stdout:{write:s=>{output+=s;}}}),0);const result=JSON.parse(output);assert.equal(result.hostId,f.hostId);assert.equal(result.url,'https://127.0.0.1:1234/mcp');assert.equal(path.basename(result.caFile),'ca.pem');assert.ok(!output.includes(f.accessToken));});
test('local hostname endpoints are accepted while public names and malformed hosts fail closed',()=>{
 for(const host of ['workstation','workstation.local','LOCALHOST','desk-01'])assert.equal(new URL(validateURL(`https://${host}:3922/mcp`)).port,'3922');
 for(const host of ['example.com','desk.corp.example','desk.local.example','-desk','desk-','a_b.local'])assert.throws(()=>validateURL(`https://${host}:3922/mcp`));
});
test('initial numeric IP and port precede cache; legacy preferred hostname is not probed',async t=>{
 const f=fixture(t),preferred='https://127.0.0.1:3922/mcp',cached='https://127.0.0.1:4242/mcp',found='https://127.0.0.1:4343/mcp';importCredentials({...f,initialUrl:preferred,preferredUrl:'https://desk.local:3922/mcp'},f);
 const cache=path.join(f.stateDirectory,'hosts',f.hostId,'endpoint.json');const reset=()=>fs.writeFileSync(cache,JSON.stringify({hostId:f.hostId,url:cached}));let attempts=[],broadcasts=0;
 const discover=async()=>{broadcasts++;return [found];};const probe=success=>async(url)=>{attempts.push(url);if(url!==success)throw Object.assign(Error('offline'),{code:'ECONNREFUSED'});return {hostId:f.hostId,startedAt:100};};
 reset();assert.equal((await resolveEndpoint({...f,request:probe(preferred),discover})).url,preferred);assert.deepEqual(attempts,[preferred]);assert.equal(broadcasts,0);
 reset();attempts=[];assert.equal((await resolveEndpoint({...f,request:probe(cached),discover})).url,cached);assert.deepEqual(attempts,[preferred,cached]);assert.equal(broadcasts,0);
 reset();attempts=[];assert.equal((await resolveEndpoint({...f,request:probe(found),discover})).url,found);assert.deepEqual(attempts.slice(0,2),[preferred,cached]);assert.equal(broadcasts,1);assert.ok(attempts.includes(found));
});
test('status request wall deadline bounds a socket that never completes TLS',async t=>{
 const net=require('node:net'),sockets=new Set();const server=net.createServer(socket=>{sockets.add(socket);socket.once('close',()=>sockets.delete(socket));});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(async()=>{for(const socket of sockets)socket.destroy();await new Promise(resolve=>server.close(resolve));});
 const start=Date.now();await assert.rejects(requestStatus(`https://127.0.0.1:${server.address().port}/mcp`,{certificatePem:undefined,accessToken:'a'.repeat(64),timeoutMs:80}),{code:'HOST_UNREACHABLE'});assert.ok(Date.now()-start<2000,'hard deadline must include TLS handshake time');
});
test('numeric initialUrl metadata rejects hostnames and legacy numeric addresses remain usable',async t=>{
 const f=fixture(t),url='https://127.0.0.1:3922/mcp';assert.throws(()=>importCredentials({...f,initialUrl:'https://desk.local:3922/mcp'},f),/numeric IP/);
 importCredentials({...f,preferredUrl:'https://desk.local:3922/mcp',addresses:['https://desk.local:3922/mcp',url]},f);const tried=[];assert.equal((await resolveEndpoint({...f,request:async target=>{tried.push(target);return {hostId:f.hostId,startedAt:1};},discover:async()=>{throw Error('unexpected discovery');}})).url,url);assert.deepEqual(tried,[url]);
});
test('failed endpoints are deduplicated and newly updated shared cache is reread',async t=>{
 const f=fixture(t),old='https://127.0.0.1:3922/mcp',fresh='https://127.0.0.1:3923/mcp';importCredentials({...f,initialUrl:old},f);const cache=path.join(f.stateDirectory,'hosts',f.hostId,'endpoint.json');fs.writeFileSync(cache,JSON.stringify({hostId:f.hostId,url:old}));const tried=[];
 assert.equal((await resolveEndpoint({...f,request:async url=>{tried.push(url);if(url===old){fs.writeFileSync(cache,JSON.stringify({hostId:f.hostId,url:fresh}));throw Error('old endpoint offline');}return {hostId:f.hostId,startedAt:1};},discover:async()=>{throw Error('cache should win');}})).url,fresh);assert.deepEqual(tried,[old,fresh]);
 fs.writeFileSync(cache,'invalid JSON');tried.length=0;let discoveries=0;assert.equal((await resolveEndpoint({...f,request:async url=>{tried.push(url);if(url===old)throw Error('offline');return {hostId:f.hostId,startedAt:2};},discover:async()=>{discoveries++;return [old,old,fresh];}})).url,fresh);assert.equal(discoveries,1);assert.deepEqual(tried,[old,fresh]);
});
test('force discovery bypasses a healthy initial URL and cache',async t=>{
 const f=fixture(t),old='https://127.0.0.1:3922/mcp',fresh='https://127.0.0.1:3923/mcp';importCredentials({...f,initialUrl:old},f);fs.writeFileSync(path.join(f.stateDirectory,'hosts',f.hostId,'endpoint.json'),JSON.stringify({hostId:f.hostId,url:old}));let discoveries=0;const tried=[];
 const result=await resolveEndpoint({...f,force:true,request:async url=>{tried.push(url);return {hostId:f.hostId,startedAt:1};},discover:async()=>{discoveries++;return [fresh];}});assert.equal(result.url,fresh);assert.equal(discoveries,1);assert.deepEqual(tried,[fresh]);
});
test('unreadable endpoint cache is best effort while credentials and CA permissions remain fatal',async t=>{
 const f=fixture(t),old='https://127.0.0.1:3922/mcp',fresh='https://127.0.0.1:3923/mcp';importCredentials({...f,initialUrl:old},f);const host=path.join(f.stateDirectory,'hosts',f.hostId),cache=path.join(host,'endpoint.json');const nativeOpen=fs.openSync;let blocked=cache,blockedCode='EACCES';
 fs.openSync=function(file,...args){if(file===blocked)throw Object.assign(Error(f.accessToken+' forbidden'),{code:blockedCode});return nativeOpen.call(fs,file,...args);};
 try{let discoveries=0;const tried=[];const settings={...f,request:async url=>{tried.push(url);if(url===old)throw Error('offline');return {hostId:f.hostId,startedAt:1};},discover:async()=>{discoveries++;return [fresh];}};
 for(const code of ['EACCES','EPERM']){blockedCode=code;tried.length=0;const result=await resolveEndpoint(settings);assert.equal(result.url,fresh);assert.deepEqual(tried,[old,fresh]);assert.ok(!JSON.stringify(result).includes(f.accessToken));}assert.equal(discoveries,2);blockedCode='EACCES';
 for(const file of ['credentials.json','ca.pem']){blocked=path.join(host,file);await assert.rejects(resolveEndpoint(settings),{code:'EACCES'});}assert.equal(discoveries,2);
 }finally{fs.openSync=nativeOpen;}
});

test('POSIX discovery credentials are private to their owner',{skip:process.platform==='win32'?'Windows uses inherited DACLs rather than POSIX permission bits':false},t=>{const f=fixture(t);importCredentials(f,f);assert.equal(fs.statSync(path.join(f.stateDirectory,'hosts',f.hostId,'credentials.json')).mode&0o777,0o600);});
